### ISSUE TITLE
Next button functionality 

### ISSUE THREAD

**Issue by ArunParthiban10** [Ashmawy/dockerSwift#6]
The Next button in the apps screen should post to http://127.0.0.1:5000/apps with a JSON body that looks like 
{"os": "ubuntu", "apps": ["vim"]}

Where os is the os selected and apps is a list of apps selected. 
The response for the above request will be 
{
  "dockerfile": "FROM ubuntu\nRUN apt-get install vim\n"
}

Which **## may** be rendered and displayed to the user to show the what's happening at each step.

**Comment by Ashmawy** [comment]
Resolved in latest commit.
