### ISSUE TITLE
Commands 

### ISSUE THREAD

**Issue by ArunParthiban10** [Ashmawy/dockerSwift#8]
A get return to http://127.0.0.1:5000/commands returns a list of available commands .

The post expects a json with 3 keys : 

initial  -> Initial docker file returned in /apps 
type    -> RUN, COPY, EXPOSE , as retuned by the GET request 
instruction -> The instruction to go with the type : 

Example :

A POST with the following JSON

{"initial": "FROM: Ubuntu .....\n","type": "RUN", "instruction": "/dev/app.py"}

The above will return : 

{
  "dockerfile": "FROM: Ubuntu ..... 
                          RUN /dev/app.py"  
}

**Comment by Ashmawy** [comment]
Resolved in latest commit.
